# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfxview', '0002_atbat_end_tfs_zulu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
